HomeDevices.Net.Server.Web/Areas/Data/Pages/Details.cshtml.cs
using HomeDevices.Net.Server.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HomeDevices.Net.Server.Net.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeDevices.Net.Server.Web.Areas.Data.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly HomeDevices.Net.Server.Net.Data.ApplicationDbContext _context;

        public DetailsModel(HomeDevices.Net.Server.Net.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public RuuviTag RuuviTag { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RuuviTag = await _context.RuuviTags.FirstOrDefaultAsync(m => m.Id == id);

            if (RuuviTag == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

HomeDevices.Net.Server.Web/Areas/Data/Pages/Index.cshtml.cs
using HomeDevices.Net.Server.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeDevices.Net.Server.Net.Data;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace HomeDevices.Net.Server.Web.Areas.Data.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public IList<RuuviTag> RuuviTags { get; set; }
        public int TotalRows { get; set; }
        public DateTime LogStart { get; set; }
        public DateTime LogEnd { get; set; }
        [BindProperty]
        public DateTime SearchStart { get; set; }
        [BindProperty]
        public DateTime SearchEnd { get; set; }

        [BindProperty]
        public Device Device { get; set; }

        [BindProperty]
        public List<SelectListItem> Devices { get; set; }

        [BindProperty]
        public List<SelectListItem> Locations { get; set; }

        [BindProperty]
        public Location Location { get; set; }

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task OnGetAsync()
        {
            //await GenerateTestData();
            await GetDefaultData();
            RuuviTags = await _context.RuuviTags
                .Where(a => a.CreatedOn >= SearchStart && a.CreatedOn <= SearchEnd)
                .OrderByDescending(o => o.CreatedOn)
                .AsNoTracking()
                .ToListAsync();
        }

        private async Task GetDefaultData()
        {
            TotalRows = await _context.RuuviTags.CountAsync();
            LogStart = await _context.RuuviTags.MinAsync(t => t.CreatedOn);
            LogEnd = await _context.RuuviTags.MaxAsync(t => t.CreatedOn);

            Locations = await _context.Locations.Select(a =>
                                  new SelectListItem
                                  {
                                      Value = a.Id.ToString(),
                                      Text = a.Name
                                  }).ToListAsync();

            Devices = await _context.Devices.Select(a =>
                                  new SelectListItem
                                  {
                                      Value = a.Id.ToString(),
                                      Text = a.Name
                                  }).ToListAsync();

            if (SearchStart == DateTime.MinValue)
                SearchStart = DateTime.Now.AddDays(-1);
            if (SearchEnd == DateTime.MinValue)
                SearchEnd = DateTime.Now;
        }

        public async Task<IActionResult> OnPostDeleteAllAsync()
        {
            await _context.Database.ExecuteSqlRawAsync("TRUNCATE TABLE RuuviTags");
            RuuviTags = new List<RuuviTag>();
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteByDateAsync(DateTime start, DateTime end)
        {
            var items = await _context.RuuviTags.Where(r => r.CreatedOn >= start && r.CreatedOn <= end).ToListAsync();
            if (items.Any())
            {
                _context.RuuviTags.RemoveRange(items);
                await _context.SaveChangesAsync();
            }

            await GetDefaultData();

            return Page();
        }

        private async Task GenerateTestData()
        {
            for (int i = 0; i < 100; i++)
            {
                RuuviTag tag = new()
                {
                    AccelerationX = i,
                    AccelerationY = i,
                    AccelerationZ = i,
                    AirPressure = i,
                    BatteryVoltage = i,
                    CreatedOn = DateTime.Now,
                    DataFormat = 1,
                    Deleted = false,
                    Humidity = i,
                    Id = Guid.NewGuid().ToString(),
                    MacAddress = Guid.NewGuid().ToString(),
                    MeasurementSequenceNumber = i,
                    MovementCounter = i,
                    Temperature = i,
                    TxPower = i
                };

                _context.RuuviTags.Add(tag);
            }

            await _context.SaveChangesAsync();
        }

        public async Task<IActionResult> OnPostSearchByTermsAsync(
            string locationId,
            string deviceId)
        {
            await GetDefaultData();

            if (!string.IsNullOrWhiteSpace(deviceId))
            {
                Device = await _context.Devices.FindAsync(deviceId);
                if (Device != null)
                {
                    RuuviTags = await _context.RuuviTags
                        .Where(r => r.CreatedOn >= SearchStart && r.CreatedOn <= SearchEnd && r.MacAddress == Device.MacAddress)
                        .OrderByDescending(o => o.CreatedOn)
                        .AsNoTracking()
                        .ToListAsync();
                }
            }
            else if (!string.IsNullOrWhiteSpace(locationId))
            {
                Location = await _context.Locations.FindAsync(locationId);
                if (Location != null)
                {
                    List<string> macs = Location.Devices.Select(d => d.MacAddress).ToList();
                    if (macs.Any())
                    {
                        RuuviTags = await _context.RuuviTags
                            .Where(r => r.CreatedOn >= SearchStart && r.CreatedOn <= SearchEnd && macs.Contains(r.MacAddress))
                            .OrderByDescending(o => o.CreatedOn)
                            .AsNoTracking()
                            .ToListAsync();
                    }
                }
            }
            else
            {
                RuuviTags = await _context.RuuviTags
                    .Where(r => r.CreatedOn >= SearchStart && r.CreatedOn <= SearchEnd)
                    .OrderByDescending(o => o.CreatedOn)
                    .AsNoTracking()
                    .ToListAsync();
            }

            return Page();
        }

    }
}

HomeDevices.Net.Server.Web/Areas/Devices/Pages/Details.cshtml.cs
using HomeDevices.Net.Server.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HomeDevices.Net.Server.Net.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeDevices.Net.Server.Web.Areas.Devices.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly HomeDevices.Net.Server.Net.Data.ApplicationDbContext _context;

        public DetailsModel(HomeDevices.Net.Server.Net.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Device Device { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Device = await _context.Devices.Include(l => l.Location).FirstOrDefaultAsync(m => m.Id == id);

            if (Device == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

HomeDevices.Net.Server.Web/Areas/Locations/Pages/Details.cshtml.cs
using HomeDevices.Net.Server.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HomeDevices.Net.Server.Net.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeDevices.Net.Server.Web.Areas.Locations.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly HomeDevices.Net.Server.Net.Data.ApplicationDbContext _context;

        public DetailsModel(HomeDevices.Net.Server.Net.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Location Location { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Location = await _context.Locations.FirstOrDefaultAsync(m => m.Id == id);

            if (Location == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

HomeDevices.Net.Server.Web/Areas/Data/Pages/Details.cshtml
@page
@model HomeDevices.Net.Server.Web.Areas.Data.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RuuviTag</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.UpdatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.UpdatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.Deleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.Deleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.DataFormat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.DataFormat)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.Humidity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.Humidity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.Temperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.Temperature)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.AirPressure)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.AirPressure)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.AccelerationX)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.AccelerationX)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.AccelerationY)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.AccelerationY)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.AccelerationZ)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.AccelerationZ)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.BatteryVoltage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.BatteryVoltage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.TxPower)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.TxPower)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.MovementCounter)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.MovementCounter)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.MeasurementSequenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.MeasurementSequenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RuuviTag.MacAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RuuviTag.MacAddress)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.RuuviTag.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

HomeDevices.Net.Server.Web/Areas/Data/Pages/Index.cshtml
@page
@model HomeDevices.Net.Server.Web.Areas.Data.Pages.IndexModel
@{
}

<div class="jumbotron" id="top">
    <div class="row row-cols-2">
        <div class="col-md-2"><img height="50" src="~/img/data.svg" /></div>
        <div class="col">
            <h5>Data in database</h5>
            <p>There is <b>@Model.TotalRows</b> rows in database</p>
            <p>Log data contains data from period @Model.LogStart - @Model.LogEnd</p>
        </div>
    </div>
</div>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Search
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h4>Search data with these search terms.</h4>
                <form method="post">
                    <div class="row">
                        <div class="col">
                            <label asp-for="SearchStart" class="form-label">CreatedOn start</label>
                            <input type="datetime-local" asp-for="SearchStart" class="form-control" />
                        </div>
                        <div class="col">
                            <label asp-for="SearchEnd" class="form-label">CreatedOn end</label>
                            <input type="datetime-local" asp-for="SearchEnd" class="form-control" />
                        </div>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Location" class="form-label"></label>
                        <select id="locationId" name="locationId" asp-items="Model.Locations" class="form-control">
                            <option value="">Select location</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Device" class="form-label"></label>
                        <select id="deviceId" name="deviceId" asp-items="Model.Devices" class="form-control">
                            <option value="">Select device</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <input type="submit" asp-page-handler="SearchByTerms" value="Search" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Delete Data
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <div>
                    <form method="post">
                        <div class="form-group">
                            <input type="submit" asp-page-handler="DeleteALl" value="Delete All" class="btn btn-danger" />
                        </div>
                    </form>
                    <hr />
                    <form method="post">
                        <div class="mb-3">
                            <label for="start" class="form-label"></label>
                            <input type="datetime-local" id="start" name="start" class="form-control" />
                        </div>
                        <div class="mb-3">
                            <label for="end" class="form-label"></label>
                            <input type="datetime-local" id="end" name="end" class="form-control" />
                        </div>
                        <div class="mb-3">
                            <input type="submit" asp-page-handler="DeleteByDate" value="Delete By Time" class="btn btn-danger" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@if (Model.RuuviTags != null)
{
    <table class="table table-bordered" id="tagsTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RuuviTags[0].CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RuuviTags[0].MacAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RuuviTags[0].Temperature)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RuuviTags[0].Humidity)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.RuuviTags)
            {
                <tr>
                    <td>
                        <a asp-page="./Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.CreatedOn)</a>
                    </td>
                    <td>
                        <a asp-page="./DetailsByMac" asp-area="Devices" asp-route-mac="@item.MacAddress">@Html.DisplayFor(modelItem => item.MacAddress)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Temperature)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Humidity)
                    </td>
                    <td>
                        <a asp-page="./Details" asp-route-id="@item.Id"><i class="fas fa-fw fa-info"></i></a>
                        <a asp-page="./Edit" asp-route-id="@item.Id"><i class="fas fa-fw fa-edit"></i></a>
                        <a asp-page="./Delete" asp-route-id="@item.Id"><i class="fas fa-fw fa-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@section Scripts {
<!-- Page level plugins -->
<script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>

<script>
    $(document).ready(function () {
        $('#tagsTable').DataTable({
            stateSave: true,
            "order": [[ 1, "desc" ]]
        });
    });
</script>
}