HomeDevices.Net.Server.Web/Areas/Service/Pages/Index.cshtml.cs
using HomeDevices.Net.Server.Web.Pages;
using HomeDevices.Net.Server.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace HomeDevices.Net.Server.Web.Areas.Service.Pages
{
    public class IndexModel : BasePageModel
    {
        private readonly RuuviService _ruuviService;
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(RuuviService ruuviService,
            ILogger<IndexModel> logger, IHttpClientFactory clientFactory) : base(clientFactory)
        {
            _ruuviService = ruuviService;
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            await OnGetHealthAsync();
        }
        public async Task OnPostStartAsync()
        {
            await _ruuviService.StartAsync(new CancellationToken());
            await OnGetHealthAsync();
        }

        public async Task OnPostStopAsync()
        {
            await _ruuviService.StopAsync(new CancellationToken());
            await OnGetHealthAsync();
        }
    }
}

HomeDevices.Net.Server.Web/Areas/Service/Pages/Index.cshtml
@page "Index"
@model HomeDevices.Net.Server.Web.Areas.Service.Pages.IndexModel

<div class="jumbotron">
    <div class="row row-cols-2">
        <div class="col-md-2"><img height="50" src="~/img/service.svg" /></div>
        <div class="col"><h5>Background Service</h5></div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4>Control Background Service</h4>
    </div>
    <div class="card-body">
        <div class="alert alert-primary" role="alert">
            <b>Service status: </b>@ViewData["Status"]
        </div>
    </div>
    <div class="card-footer align-content-center">
        <form method="post">
            <button type="submit" asp-page-handler="Start" class="btn btn-primary">Start</button>
            <button type="submit" asp-page-handler="Stop" class="btn btn-secondary">Stop</button>
        </form>
    </div>
</div>